### ISSUE TITLE
TJQKA is not evaluated as Straight. High Card  with Ace 's power is error.

### ISSUE THREAD

**Issue by tidus5** [mashlol/Poker-Hand-Evaluator#1]
TJQKA is not evaluated as Straight.

============================================
Player 1's hand:
King of Spades
Queen of Spades
Jack of Spades
Ten of Spades
Ace of Clubs

Player 2's hand:
Two of Spades
Three of Spades
Four of Spades
Jack of Spades
Queen of Clubs

Player 1 got a High Card valued as 12.111008644104004
Player 2 got a High Card valued as 11.100302696228027
Player 1 wins

 High Card  with Ace 's power is error.

===================================================

Player 1's hand:
Seven of Spades
Queen of Spades
Five of Spades
Ten of Spades
Ace of Clubs

Player 2's hand:
Two of Spades
Three of Spades
Four of Spades
Jack of Spades
Queen of Clubs

Player 1 got a High Card valued as 11.090603828430176
Player 2 got a High Card valued as 11.100302696228027
Player 2 wins

**Comment by mashlol** [comment]
Hey @tidus5, I wrote this in 2012 as a fun little project, haven't used it for anything and am not maintaining it.  If you'd like, I can give you push access and you can update it to fix these issues?

**Comment by tidus5** [comment]
@mashlol  Thank you for replying. I just need to write a texas poker evaluator, so I searched and found this repo. Thanks for the idea in your codes, I have wrote my version of evaluator.
I would like to fix this issue if you give me the push access. Thank you. 
 :D

**Comment by mashlol** [comment]
Gave push access
